remove hardcoded yaml-cpp path from CMakeLists.txt
NVIDIA/TorchFort pull request #5
Opened 2023-08-31 17:05 UTC by TomMelt

`CMakeLists.txt` and `examples/cpp/cart_pole/CMakeLists.txt` contain hardcoded paths to `yaml-cpp`

These has been removed in favour of using `env` variables

* `YAML_LIBRARY`
* `YAML_INCLUDE_DIRS`

2023-09-05 12:13 UTC, azrael417 commented
LGTM. Josh, any comments?

2023-09-05 17:17 UTC, romerojosh requested changes
Thanks for working on improving the build for non-Docker users @TomMelt!

Left a couple of comments/changes. Additionally, before we can merge, can you update the `Dockerfile` to include the definition of this new env var to the TorchFort build line, for example, something like:
```
RUN cd /torchfort && mkdir build && cd build && \
    cmake -DCMAKE_INSTALL_PREFIX=/opt/torchfort \
    -DNVHPC_CUDA_VERSION=11.8 \
    -DCMAKE_PREFIX_PATH="`python -c 'import torch;print(torch.utils.cmake_prefix_path)'`;/opt/nvidia/hpc_sdk/Linux_x86_64/23.5/cmake" \
    -DYAML_LIBRARY=/opt/yaml-cpp/lib \
    -DYAML_INCLUDE_DIRS=/opt/yaml-cpp/include \
    .. && \
    make -j install && \
    cd / && rm -rf torchfort
```

2023-09-05 17:17 UTC, romerojosh commented on CMakeLists.txt
> +target_link_libraries(${PROJECT_NAME} PRIVATE ${YAML_LIBRARY}/libyaml-cpp.a)
```suggestion
target_link_libraries(${PROJECT_NAME} PRIVATE ${YAML_CPP_ROOT}/lib/libyaml-cpp.a)
```
Instead of defining separate YAML_LIBRARY and YAML_INCLUDE_DIRS env vars, could we use a single env var like YAML_CPP_ROOT?

2023-09-05 17:17 UTC, romerojosh commented on CMakeLists.txt
> +    ${YAML_INCLUDE_DIRS}
```suggestion
    ${YAML_CPP_ROOT}/include
```

2023-09-05 17:17 UTC, romerojosh commented on examples/cpp/cart_pole/CMakeLists.txt
> +    ${YAML_INCLUDE_DIRS}
```suggestion
    ${YAML_CPP_ROOT}/include
```

2023-09-05 17:17 UTC, romerojosh commented on examples/cpp/cart_pole/CMakeLists.txt
> +  target_link_libraries(${tgt} PRIVATE ${YAML_LIBRARY}/libyaml-cpp.a)
```suggestion
  target_link_libraries(${tgt} PRIVATE ${YAML_CPP_ROOT}/lib/libyaml-cpp.a)
```

2023-09-06 08:47 UTC, TomMelt commented
> Thanks for working on improving the build for non-Docker users @TomMelt!
> 
> Left a couple of comments/changes. Additionally, before we can merge, can you update the `Dockerfile` to include the definition of this new env var to the TorchFort build line, for example, something like:
> 
> ```
> RUN cd /torchfort && mkdir build && cd build && \
>     cmake -DCMAKE_INSTALL_PREFIX=/opt/torchfort \
>     -DNVHPC_CUDA_VERSION=11.8 \
>     -DCMAKE_PREFIX_PATH="`python -c 'import torch;print(torch.utils.cmake_prefix_path)'`;/opt/nvidia/hpc_sdk/Linux_x86_64/23.5/cmake" \
>     -DYAML_LIBRARY=/opt/yaml-cpp/lib \
>     -DYAML_INCLUDE_DIRS=/opt/yaml-cpp/include \
>     .. && \
>     make -j install && \
>     cd / && rm -rf torchfort
> ```

Hi @romerojosh , I have update the `Dockerfile` to include the `YAML_CPP_ROOT` environment variable. It should be sufficient.

https://github.com/TomMelt/TorchFort/blob/218ac7de1c0b609a18cae6353ef72c4baeb88f89/docker/Dockerfile#L48

2023-09-07 14:54 UTC, romerojosh approved these changes
LGTM! Thanks for the PR!

2023-09-07 14:54 UTC, merged